project:
  type: website
  output-dir: docs
  
website:
  title: "IU BHDS Visualization Gallery"
  navbar:
    left:
      - href: index.qmd
        text: Home

  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Visualization Guides"
        contents:
          - href: enrollment.qmd
            text: "Enrollment Tracking"
          - href: raincloud.qmd
            text: Raincloud Plots
          - href: consort.qmd
            text: CONSORT Diagrams
          - href: ae_vis.qmd
            text: Adverse Event Plots
      - section: "R Markdown"
        contents:
          - href: RMarkdownTips.qmd
            text: Tips
          
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



