project:
  type: website
  output-dir: docs
  
website:
  title: "IU BHDS Visualization Gallery"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - enrollment.qmd
      - raincloud.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Templates"
        contents:
          - href: enrollment.qmd
            text: "Enrollemnt"
          - raincloud.qmd
      - section: "R Markdown Tips"
        contents:
          - RMarkdownTips.qmd
          
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



