---
title: "Common Charts"
---


```{r setup, include=FALSE}

# Needed Package names
packages <- c("tidyverse", "kableExtra", "ggplot2", "scales", "RColorBrewer", "zoo", "readxl" , "rmarkdown", "htmltools", "palmerpenguins")
# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}
# Attach Packages
invisible(lapply(packages, library, character.only = TRUE))

#Plot elements
# gg_text = theme(text = element_text(family = "Times"))
gg_scaley = scale_y_continuous(breaks = pretty_breaks())
gg_scalexd = scale_x_date(breaks = pretty_breaks())
```

```{r, include = F}
datafile <- read_xlsx("I:/Projects/InfoEng/QuartoRMD/vizgallery/EnrollReport_Input_Example.xlsx",  guess_max = 1000)

enrolldata <- datafile |> 
    mutate(enrol_d=as.Date(enrol_d)) |> 
    mutate(sex=toupper(sex)) |>  
    mutate(age=as.numeric(floor(age))) |> 
    mutate(enrol_w=floor_date(as.Date(enrol_d), "week")) 

```

```{r}
#| echo: TRUE
#| layout-ncol: 1
#| fig-cap: 
#|   - "Default Settings"
#| code-fold: true
#| code-summary: "Display code"

sextotal <- penguins |> 
  group_by(sex) |> 
  summarize(count=n())


sexenroll1 = ggplot(data=sextotal, aes(x=sex, y=count, fill=sex)) + 
  geom_bar(stat="identity", alpha=0.8, color="black" )

plot(sexenroll1)
```

```{r}
#| echo: TRUE
#| layout-ncol: 1
#| fig-cap: 
#|   - "Custom Settings"
#| code-fold: true
#| code-summary: "Display code"
#| code-link: true
#| code-block-bg: true
#| code-block-border-left: "#31BAE9"

sexenroll2 = ggplot(data=sextotal, aes(x=sex, y=count, fill=sex)) + 
  geom_bar(stat="identity", alpha=0.8, color="black" )+
  coord_flip()+
  scale_fill_brewer(palette="BuPu")+
  xlab("") + ylab("Number") + 
  labs(title = "Enrollment by Sex") +
  theme_classic()+
  theme(plot.title = element_text(hjust = 0), legend.position="bottom", legend.title = element_blank(), 
        plot.subtitle = element_text(size=9), plot.caption = element_text(hjust=0)) 

plot(sexenroll2)

```

